[32m2025-06-18 22:20:05 +0530[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a9e3658c-e334-4f28-84f7-b694ed334d85 - 248500 - LOGS_CAPTURED - Started capturing logs in process (pid: 248500).
[32m2025-06-18 22:20:05 +0530[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a9e3658c-e334-4f28-84f7-b694ed334d85 - 248500 - raw_rides - STEP_START - Started execution of step "raw_rides".
[32m2025-06-18 22:20:05 +0530[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - a9e3658c-e334-4f28-84f7-b694ed334d85 - 248500 - raw_rides - STEP_FAILURE - Execution of step "raw_rides" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "raw_rides"::

duckdb.IOException: IO Error: Cannot open file "c:\\bike_share.db": Access is denied.


Stack Trace:
  File "C:\Users\Parth Suyal\Desktop\bike_share_analysis\venv\Lib\site-packages\dagster\_core\execution\plan\utils.py", line 54, in op_execution_error_boundary
    yield
  File "C:\Users\Parth Suyal\Desktop\bike_share_analysis\venv\Lib\site-packages\dagster\_utils\__init__.py", line 445, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "C:\Users\Parth Suyal\Desktop\bike_share_analysis\venv\Lib\site-packages\dagster\_core\execution\plan\compute_generator.py", line 124, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Parth Suyal\Desktop\bike_share_analysis\venv\Lib\site-packages\dagster\_core\execution\plan\compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Parth Suyal\Desktop\bike_share_analysis\dagster_bike_share\assets\ingestion.py", line 31, in raw_rides
    conn = duckdb.connect("bike_share.db")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0m
